language: node_js
node_js:
  - "9"
before_script:
  - npm install
script: 
  - npm run build
  - cp ./dist/examen-app/index.html ./dist/examen-app/404.html 
deploy:
  local-dir: dist/examen-app
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
notifications:
  email: false
  slack: diginamic:nIQwPkWk2zfq2fjtzxMWhuBD#examen-app-d12